# Generated by Django 3.1.2 on 2020-11-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('picture', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=1000)),
                ('included', models.CharField(max_length=1500)),
                ('Pricing_min', models.CharField(default='', max_length=100)),
                ('Pricing_max', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
