# Generated by Django 3.1.2 on 2020-11-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('picture', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=1000)),
                ('included', models.CharField(max_length=1500)),
                ('Pricing', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
