# Generated by Django 3.1.2 on 2020-11-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201113_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('picture', models.ImageField(upload_to='')),
                ('Pricing', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
