# Generated by Django 3.1.2 on 2020-11-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_servicebooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Package_Name', models.CharField(max_length=150)),
                ('Your_Name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100)),
                ('Mobile_Number', models.CharField(max_length=50)),
                ('message', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=150)),
                ('Your_Name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100)),
                ('Mobile_Number', models.CharField(max_length=50)),
                ('message', models.CharField(default='', max_length=400)),
                ('Demo_link', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
