# Generated by Django 3.1.2 on 2020-11-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_packagebooking_productbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbooking',
            name='Demo_link',
        ),
        migrations.AddField(
            model_name='product',
            name='Demo_link',
            field=models.CharField(default='', max_length=500),
        ),
    ]
